name: dbt-run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install "dbt-bigquery==1.8.*"  # ensure dbt is installed
          dbt --version

      - name: Write GCP service account key to file
        run: |
          mkdir -p .gcloud
          echo "${GCP_SA_KEY}" > .gcloud/dbt-service-account.json
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Run dbt
        working-directory: ./dbt
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/.gcloud/dbt-service-account.json
        run: |
          dbt deps
          dbt seed --profiles-dir ..
          dbt run --profiles-dir ..
